## Actividad 9

Tipo de datos y objetos
TGAD - Taller de Programación para el análisis de datos

Obtenga el siguiente dataframe “Medical Insurance Cost Prediction” de
[https://www.kaggle.com/datasets/mohankrishnathalla/medical-insurance-cost-prediction](https://www.kaggle.com/datasets/mohankrishnathalla/medical-insurance-cost-prediction)

In [1]:
#se instala el módulo
!pip -q install kagglehub

#se cargan librerías
import kagglehub
import pandas as pd

#se descarga el dataset de kaggle
ruta_dataset = kagglehub.dataset_download("mohankrishnathalla/medical-insurance-cost-prediction")
print(ruta_dataset)

#se crea un dataframe con el archivo csv
df = pd.read_csv(ruta_dataset + "/medical_insurance.csv")

#se observa el dataframe
df.head()

Using Colab cache for faster access to the 'medical-insurance-cost-prediction' dataset.
/kaggle/input/medical-insurance-cost-prediction

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
0,75722,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,...,0,1,0,1,0,2,0,1,0,0
1,80185,79,Female,North,Urban,12800.0,No HS,Married,Employed,3,...,0,1,1,0,0,1,0,1,1,0
2,19865,68,Male,North,Rural,40700.0,HS,Married,Retired,5,...,0,0,1,1,0,2,1,0,1,0
3,76700,15,Male,North,Suburban,15600.0,Some College,Married,Self-employed,5,...,0,0,0,1,0,0,1,0,0,0
4,92992,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,...,0,1,0,2,0,1,1,0,1,0

In [2]:
# 1- Genere una muestra aleatoria simple sin reemplazo de 1000 casos. 

muestra_1 = df.sample(n=1000, replace=False, random_state=42)
print('Cantidad de casos en la muestra 1:', muestra_1.shape[0])
muestra_1.head()

Cantidad de casos en la muestra 1: 1000

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
75721,48299,60,Male,East,Urban,30600.0,Masters,Single,Employed,4,...,0,0,1,1,0,1,0,1,1,1
80184,81048,40,Male,North,Rural,55900.0,Some College,Married,Employed,2,...,0,0,0,0,0,0,1,0,0,0
19864,92755,55,Male,East,Urban,226200.0,HS,Married,Employed,3,...,0,0,0,0,0,1,0,0,1,0
76699,46008,40,Female,Central,Suburban,70700.0,Some College,Married,Employed,3,...,0,1,0,1,0,0,1,0,0,0
92991,76982,70,Male,West,Urban,107200.0,No HS,Single,Employed,2,...,0,1,0,0,0,0,1,1,1,0

In [3]:
# 2- Genere una muestra estratificada asumiendo que el estrato es el género, de 1000 casos.

muestra_2_partes = []
proporcion_total = len(df)
resto_por_asignar = 1000

for i, (sexo, grupo) in enumerate(df.groupby('sex')):
    if i < df['sex'].nunique() - 1:
        n_sexo = round(len(grupo) * 1000 / proporcion_total)
        resto_por_asignar = resto_por_asignar - n_sexo
    else:
        n_sexo = resto_por_asignar

    muestra_2_partes.append(grupo.sample(n=n_sexo, replace=False, random_state=42))

muestra_2 = pd.concat(muestra_2_partes)

if muestra_2.shape[0] > 1000:
    muestra_2 = muestra_2.sample(n=1000, random_state=42)

print('Cantidad de casos en la muestra 2:', muestra_2.shape[0])
muestra_2['sex'].value_counts()

Cantidad de casos en la muestra 2: 1000

sex
Female    492
Male      488
Other      20
Name: count, dtype: int64

In [4]:
# 3- Genere una muestra por conglomerado tomando como conglomerado a la región, donde cada 
# conglomerado (5 en total) tenga 100 casos.

muestra_3_partes = []

for region, grupo in df.groupby('region'):
    muestra_3_partes.append(grupo.sample(n=100, replace=False, random_state=42))

muestra_3 = pd.concat(muestra_3_partes)

print('Cantidad de casos en la muestra 3:', muestra_3.shape[0])
muestra_3['region'].value_counts()

Cantidad de casos en la muestra 3: 500

region
Central    100
East       100
North      100
South      100
West       100
Name: count, dtype: int64

In [5]:
# 4- Genere una nueva muestra aleatoria simple sin reemplazo de 1000 casos. Para ello primero, quite 
# del dataframe original lo casos que ya seleccionó en el punto 1.

resto_df = df.drop(muestra_1.index)
muestra_4 = resto_df.sample(n=1000, replace=False, random_state=42)

print('Cantidad de casos en la muestra 4:', muestra_4.shape[0])
muestra_4.head()

Cantidad de casos en la muestra 4: 1000

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
1074,29455,58,Male,South,Rural,47200.0,Bachelors,Single,Employed,2,...,0,0,0,0,0,1,0,1,1,0
28910,73762,53,Male,West,Rural,112500.0,Some College,Married,Self-employed,3,...,0,0,0,0,0,0,1,0,0,0
31191,72450,58,Male,Central,Suburban,52800.0,HS,Married,Retired,4,...,0,0,0,0,0,1,0,0,1,0
38185,48915,77,Male,East,Suburban,31200.0,Bachelors,Married,Retired,3,...,0,0,0,0,0,2,0,1,1,0
45759,79602,41,Male,West,Suburban,107000.0,Bachelors,Single,Employed,2,...,0,0,0,1,0,0,0,0,0,0

In [6]:
# 5- Concatene las muestra generadas en 1 y 4

muestra_final = pd.concat([muestra_1, muestra_4], ignore_index=True)
print('Cantidad de casos en la muestra final:', muestra_final.shape[0])
muestra_final.head()

Cantidad de casos en la muestra final: 2000

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
0,48299,60,Male,East,Urban,30600.0,Masters,Single,Employed,4,...,0,0,1,1,0,1,0,1,1,1
1,81048,40,Male,North,Rural,55900.0,Some College,Married,Employed,2,...,0,0,0,0,0,0,1,0,0,0
2,92755,55,Male,East,Urban,226200.0,HS,Married,Employed,3,...,0,0,0,0,0,1,0,0,1,0
3,46008,40,Female,Central,Suburban,70700.0,Some College,Married,Employed,3,...,0,1,0,1,0,0,1,0,0,0
4,76982,70,Male,West,Urban,107200.0,No HS,Single,Employed,2,...,0,1,0,0,0,0,1,1,1,0