<figure>
<center>
<img src='https://www.economicas.uba.ar/wp-content/uploads/2020/08/cropped-logo_FCE.png' />
</figure>

# **Universidad de Buenos Aires**
## **Facultad de Ciencias Económicas**

### **Taller de Programación para el Análisis de Datos**

#### **Clase 11: Descriptiva de datos**

En esta clase veremos como obtener diferentes medidas estadísticas para su posterior interpretación y análisis

**Cálculo de medidas estadísticas**

En Python hay funciones programadas que permiten obtener el cálculo de medidas estadísticas. Ciertas funciones son nativas (aquellas que no requieren de importar una librería) y otras no (es decir, resulta necesario importar uan librería para disponer de las funciones).

Generalmente, a las librerías se les asigna un alias para invocarlas de manera más simple en términso de escribir menos código.

Numpy: https://numpy.org/

Statistics: https://docs.python.org/es/dev/library/statistics.html

Scipy Stats: https://docs.scipy.org/doc/scipy/reference/stats.html

### **Librería**

In [1]:
import pandas as pd
import numpy as np
import sympy
import statistics as stats
import scipy.stats as ss
import math
import warnings
warnings.filterwarnings('ignore')
import kagglehub

### **Medidas estadísticas descriptivas**

In [2]:
path = kagglehub.dataset_download("parthpatel2130/realistic-loan-approval-dataset-us-and-canada")

print("Path to dataset files:", path)

DATA=pd.read_csv("/root/.cache/kagglehub/datasets/parthpatel2130/realistic-loan-approval-dataset-us-and-canada/versions/1/Loan_approval_data_2025.csv")
DATA.head()

Downloading to /root/.cache/kagglehub/datasets/parthpatel2130/realistic-loan-approval-dataset-us-and-canada/1.archive...

100%|██████████| 1.64M/1.64M [00:01<00:00, 1.46MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/parthpatel2130/realistic-loan-approval-dataset-us-and-canada/versions/1

,customer_id,age,occupation_status,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,product_type,loan_intent,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status
0,CUST100000,40,Employed,17.2,25579,692,5.3,895,10820,0,0,0,Credit Card,Business,600,17.02,0.423,0.023,0.008,1
1,CUST100001,33,Employed,7.3,43087,627,3.5,169,16550,0,1,0,Personal Loan,Home Improvement,53300,14.10,0.384,1.237,0.412,0
2,CUST100002,42,Student,1.1,20840,689,8.4,17,7852,0,0,0,Credit Card,Debt Consolidation,2100,18.33,0.377,0.101,0.034,1
3,CUST100003,53,Student,0.5,29147,692,9.8,1480,11603,0,1,0,Credit Card,Business,2900,18.74,0.398,0.099,0.033,1
4,CUST100004,32,Employed,12.5,63657,630,7.2,209,12424,0,0,0,Personal Loan,Education,99600,13.92,0.195,1.565,0.522,1

**Medidas de tendencia central:**

**MEDIA ARIMÉTICA**: Es el promedio simple de los valores de la variable aletoria Es muy sensible a valores atípicos siendo aquellos que se alejan del comportamiento “normal" de los datos. Su cálculo es:

\begin{align}
         \bar{X} = {\sum_{i=1}^n x_i\over n}
\end{align}

**MEDIANA**: Es el valor central (o mitad que es equivalente al 50%) cuando los datos se encuentran ordenados de manera creciente. Su cálculo permite obtener la posición donde se encuentra el valor dentro de la distribución de los datos:

\begin{align}
         X_{me}
\end{align}

Recordamos que en este caso se aplicabla la siguiente regla (siendo lo que realiza Python para el calculo, también en el caso de los percentiles):

Para obtener su valor se debe primero calcular:
Distancia=k*(n-1) donde k es el porcentaje que en este caso es 0,5

Si:
- Distancia=número entero => es la posición. Buscaré en el ´índice de mis datos dicha posición y me fijare el valor que toma la variable siendo este el valor de la mediana
- Distancia=número decimal => debo interpolar . El resultado de esta operación será el valor de la mediana

**MODA**: Es el valor más frecuente, es decir, el que más veces se repite dentro de la distribución. Si dos o mas valores son los de mayor frecuencia de aparición entonces estamos frente a una distribución multimodal:

\begin{align}
        x_{mo}
\end{align}

MEDIA ARITMÉTICA

In [3]:
DATA['annual_income'].mean() #utilizando función nativa

np.float64(50062.89204)

In [4]:
MEDIA_MUESTRAL=stats.mean(DATA['annual_income']) #utilizando la función pero de la librería stats
MEDIA_MUESTRAL

50062.89204

MEDIANA

In [5]:
DATA['annual_income'].median() #utilizando función nativa

41607.5

In [6]:
MEDIANA=stats.median(DATA['annual_income']) #utilizando la función pero de la librería stats
MEDIANA

41607.5

VALOR MODAL

In [7]:
DATA['annual_income'].mode() #utilizando función nativa

0    15000
Name: annual_income, dtype: int64

In [8]:
MODO=stats.mode(DATA['annual_income']) #utilizando la función pero de la librería stats
MODO

15000

¿Pero hay un solo valor modal?

In [9]:
MULTIMODAL=stats.multimode(DATA['annual_income']) #utilizando la función pero de la librería stats
MULTIMODAL

#obsevamos que no, solo hay un valor modal. Lo recomendable es siempre utilizar esta función por si llega a haber más de un valor modal

[15000]

**Medidas de Tendencia no central**

- Percentiles: permiten saber el porcentaje de observaciones que se encuentran por debajo de cierto valor y por encima al dividir la distribución de los datos en 100 partes iguales. Su cálculo, que brinda una posición dentro de la distribución de los valores de la variable aletoria, es:

\begin{align}
         {P_k} = {n * k\over 100}
\end{align}

Equivalencias:

${P_{10}} = {D_{1}}$

${P_{20}} = {D_{2}}$

${P_{25}} = {Q_{1}}$

${P_{30}} = {D_{3}}$

${P_{40}} = {D_{4}}$

${P_{50}} = {Q_{2}} = {D_{5}} = {X_{me}}$

${P_{60}} = {D_{6}}$

${P_{70}} = {D_{7}}$

${P_{75}} = {Q_{3}}$

${P_{80}} = {D_{8}}$

${P_{90}} = {D_{9}}$

${P_{100}} = {Q_{4}} = {D_{10}}$

Donde $D_i$ refiere a decil siendo aquel que divide al distribución de los datos en 10 partes iguales, y $Q_i$ refiere a cuartil siendo aquel que divide a la distribución de los datos en 4 partes iguales.

In [10]:
PERCENTILES=np.percentile(DATA['annual_income'], [5, 10, 25, 50, 60, 75, 90, 100]) #utlizando al librería numpy
PERCENTILES

array([ 15000.  ,  18541.9 ,  27280.5 ,  41607.5 ,  48636.4 ,  62723.25,
        91198.6 , 250000.  ])

In [ ]:
PERCENTILES[0]

**Medidas de dispersión:**

- RANGO: permite saber la amplitud del dominio de la distribución de los datos. Su cálculo es:

\begin{align}
         {Rango} = { X_{max} - X_{min}}
\end{align}

- RANGO INTERCUARTÍLICO: amplitud del intervalo donde se acumula el 50% de la distribución de los datos. Su cálculo es:

\begin{align}
         {RIC} = { Q_{3} - Q_{1}}
\end{align}

- VARIANZA MUESTRAL: indica cuanto se alejan los datos del valor medio de la distribución en términos cuadráticos. Su cálculo es:

\begin{align}
        S^2= {\sum_{i=1}^n (x_i - \bar{X})^2\over n-1}
\end{align}

- DESVÍO MUESTRAL: indica cuanto se alejan los datos del valor medio de la distribución en la misma unidad de media que la variable. Su cálculo es:

\begin{align}
        S= {\sqrt {S^2}}
\end{align}

- COEFICIENTE DE VARIACIÓN: mide la relación entre el desvío muestral y la media muestral. Su cálculo es:

\begin{align}
        CV= {S \over \bar{X}}
\end{align}

RANGO

In [ ]:
RANGO=DATA['annual_income'].max() - DATA['annual_income'].min() #utilizando funciones nativas
RANGO

RIC

In [ ]:
RIC=np.percentile(DATA['annual_income'], 75) - np.percentile(DATA['annual_income'], 25) #utlizando al librería numpy
RIC

VARIANZA MUESTRAL

In [ ]:
DATA['annual_income'].var() #utilizando función nativa

In [ ]:
VARIANZA=stats.variance(DATA['annual_income']) #utilizando la función pero de la librería stats
VARIANZA

DESVÍO MUESTRAL

In [ ]:
DATA['annual_income'].std() #utilizando función nativa

In [ ]:
DESVIO=stats.stdev(DATA['annual_income']) #utilizando la función pero de la librería stats
DESVIO

COEFICIENTE DE VARIACIÓN

In [ ]:
CV=DESVIO/MEDIA_MUESTRAL
CV

In [ ]:
ss.variation(DATA['annual_income'], ddof=1) #utilizando librería scipy.stats

#se recomienda utilizar ddof=1 para garantizar que la desviación estándar de la muestra se calcule como la raíz cuadrada de la varianza de la muestra insesgada

**Medidas de forma**

**COEFICIENTE DE ASIMETRÍA**: permite saber cuan dispersos se encuentran los datos respecto respecto de la media. Su cálculo es:

\begin{align}
         {A_s} = {{\sum_{i=1}^n {\left( (x_i - \bar{X}) \over {S} \right)}^3} \over n}
\end{align}

Interpretación:

- Si ${A_s} < 0 $ entonces la distribución de los datos es asimétrica negativa (concentración de datos a derecha y cola a izquierda). Entonces se cumple que ${\bar{X} < X_{me}}$

- Si ${A_s} = 0 $ entonces la distribución de los datos es simétrica. Entonces se cumple que ${\bar{X} = X_{me}}$

- Si ${A_s} > 0 $ entonces la distribución de los datos es asimétrica positiva (concentración de datos a izquierda y cola a derecha). Entonces se cumple que ${\bar{X} > X_{me}}$

**COEFICIENTE DE CURTOSIS**: permite saber como es la forma de la concentración de los datos. Su cálculo es:

\begin{align}
         {K} = {{\sum_{i=1}^n {\left( (x_i - \bar{X}) \over {S} \right)}^4} \over n}
\end{align}

Interpretación:

- Si ${K} < 3 $ entonces la distribución es platicúrtica (la forma de la distribución es más aplanada).

- Si ${K} = 3 $ entonces la distribución es mesocúrtica (la forma de la distribución no es ni muy aplanada ni muy puntiaguda).

- Si ${K} > 3 $ entonces la distribución es leptocúrtica (la forma de la distribución presenta un pico en el centro).

Las medidas de forma suelen apreciarse a través de gráficos. Particularmente, en estadística hay dos principales: histograma y boxplot. Estos ayudan a visualizar de una manera resumida varias de las medidas anteriores.

COEFICIENTE DE ASIMETRÍA

In [ ]:
CA=DATA['annual_income'].skew() #utilizando función nativa
CA

In [ ]:
ss.skew(DATA['annual_income'],bias=False) #utilizando librería scipy.stats

COEFICIENTE DE CURTOSIS

In [ ]:
CC=DATA['annual_income'].kurtosis() #utilizando función nativa
CC

In [ ]:
ss.kurtosis(DATA['annual_income'],bias=False) #utilizando librería scipy.stats

Si se quiere armar una tabla con todas las medidas calculadas, entonces:

In [ ]:
Medidas=pd.DataFrame({ 'Media Muestral': [MEDIA_MUESTRAL], 'Mediana': [MEDIANA], 'Valor Modal 1': [MODO],
                     'P05': [PERCENTILES[0]], 'P10': [PERCENTILES[1]], 'P25': [PERCENTILES[2]],'P50': [PERCENTILES[3]], 'P60': [PERCENTILES[4]],
                      'P75': [PERCENTILES[5]], 'P90': [PERCENTILES[6]],
                     'Rango': [RANGO], 'RIC': [RIC], 'Varianza Muestral': [VARIANZA], 'Desvío Muestral': [DESVIO], 'Coef Variación': [CV],
                      'Coef Asimetría': [CA], 'Coef Curtosis': [CC]
                     }).transpose()
Medidas=Medidas.reset_index(inplace=False)
Medidas.columns=['Estadísticas', 'Valores']
pd.options.display.float_format = '{:.2f}'.format #evitar notación científica y/o acotar decimales
Medidas

Es posible exportar la tabla de datos. Aparecerá en el menú de la izquierda. En los tres puntitos- > Descargar

In [ ]:
Medidas.to_csv('/content/Medidas.csv', sep=";")

Podemos escribir un programa para hacer todos los cálculos de las medidas por cada variable

In [ ]:
DATA.columns

In [ ]:
np.percentile(DATA['annual_income'], [5, 10, 25, 50, 60, 75, 90, 100])

In [ ]:
for i in DATA:
  if DATA[i].dtype=='int64' or DATA[i].dtype=='float64':
    print(f"La media de la variable {i} es: {round(stats.mean(DATA[i]),2)}")
    print(f"La mediana de la variable {i} es: {round(stats.median(DATA[i]),2)}")
    print(f"La moda de la variable {i} es: {round(stats.mode(DATA[i]),2)}")
    print(f"El P05 de la variable {i} es: {np.percentile(DATA[i], [5]).item()}")
    print(f"El P10 de la variable {i} es: {np.percentile(DATA[i], [10]).item()}")
    print(f"El P20 de la variable {i} es: {np.percentile(DATA[i], [20]).item()}")
    print(f"El P25 de la variable {i} es: {np.percentile(DATA[i], [25]).item()}")
    print(f"El P30 de la variable {i} es: {np.percentile(DATA[i], [30]).item()}")
    print(f"El P40 de la variable {i} es: {np.percentile(DATA[i], [40]).item()}")
    print(f"El P50 de la variable {i} es: {np.percentile(DATA[i], [50]).item()}")
    print(f"El P60 de la variable {i} es: {np.percentile(DATA[i], [60]).item()}")
    print(f"El P70 de la variable {i} es: {np.percentile(DATA[i], [70]).item()}")
    print(f"El P75 de la variable {i} es: {np.percentile(DATA[i], [75]).item()}")
    print(f"El P80 de la variable {i} es: {np.percentile(DATA[i], [80]).item()}")
    print(f"El P90 de la variable {i} es: {np.percentile(DATA[i], [90]).item()}")
    print(f"El P100 de la variable {i} es: {np.percentile(DATA[i], [100]).item()}")
    print(f"El RIC de la variable {i} es: {np.percentile(DATA[i], [75])-np.percentile(DATA[i], [25]).item()}")
    print(f"El máximo valor de la variable {i} es: {DATA[i].max()}")
    print(f"El mínimo valor de la variable {i} es: {DATA[i].min()}")
    print(f"El Rango de la variable {i} es: {DATA[i].max()-DATA[i].min()}")
    print(f"La varianza muestral de la variable {i} es: {DATA[i].var()}")
    print(f"El desvío muestral de la variable {i} es: {DATA[i].std()}")
    print(f"El coeficiente de asimetría de la variable {i} es: {DATA[i].skew()}")
    print(f"El coeficiente de curtosis de la variable {i} es: {DATA[i].kurtosis()}")

###**Covarianza y Correlación lineal**

**Interpretación de la Covarianza:**

- La Cov(X,Y) > 0 si la relación entre X e Y es fuertemente positiva.
 Esto es, a valores grandes de X suceden conjuntamente con
valores grandes de Y (y viceversa).

- La Cov(X,Y) < 0 si la relación entre X e Y es fuertemente negativa.
Esto es, a valores grandes de X suceden conjuntamente
con valores pequeños de Y (y viceversa).

- La Cov(X,Y)=0 no existe relación entre X e Y

**Interpretación de la correlación lineal**

- R=1 relación lineal perfectamente positiva. Esto sucederá cuando X e Y estén fuertemente  relacionadas de manera positiva.

- R= -1 relación lineal perfectamente negativa. Esto sucederá cuando X e Y estén fuertemente relacionadas de manera negativa.

- R=0  indica que existe una ausencia completa de relación lineal entre X e Y.

- 1<R<0 indica que la relación es lineal negativa:
	- Si -1<R≤ -0,8 entonces relación lineal fuertemente negativa
	- Si -0,8<R ≤ -0,5 entonces relación lineal moderadamente negativa
	- Si -0,5<R< 0 entonces relación lineal débilmente negativa

- 0<R<1 indica que la relación es lineal positiva:
	- Si 0<R< 0,5 entonces relación lineal débilmente positiva
	- Si 0<R< 0,8 entonces relación lineal moderadamente positiva
	- Si 0,8<R< 1 entonces relación lineal fuertemente positiva

Para calcular Covarianza y Correlación todas las variables deben ser numéricas

In [ ]:
DATA_1=DATA.copy()
DATA_1.head()

In [ ]:
#convertimos a categorías numéricas las variables object
for i in DATA_1:
  if DATA_1[i].dtype=='object':
    DATA_1[i]=DATA_1[i].astype('category').cat.codes
  else:
    pass

In [ ]:
DATA_1.dtypes

COVARIANZA

In [ ]:
DATA_1.cov()  #utilizando función nativa

In [ ]:
#para evitar la notación científica y/o acotar decimales

pd.options.display.float_format = '{:.2f}'.format #cantidad de decimales 8 máximo a mostrar

DATA_1.cov()  #utilizando función nativa

In [ ]:
stats.covariance(DATA_1['age'], DATA_1['annual_income']) #utilizando librería stats pero solo permite el cálculo entre dos variables

CORRELACIÓN DE PEARSON

In [ ]:
DATA_1.corr() #utilizando función nativa

In [ ]:
np.corrcoef(DATA_1['age'], DATA_1['annual_income']) #utilizando librería numpy pero solo permite el cálculo entre dos variables

###**Intervalos de Confianza**

Al trabajar con muestras, resulta importante conocer cuando cerca o lejos nos encontramos respecto del verdadero valor de la media o varianza de cada variable, principalmente

In [ ]:
#se crean funciones para el cálculo de los intervalos
def IC_MEDIA_VARDESCON(media_muestral, desv_muestral, N, alfa):
  import scipy.stats as ss
  ESTADÍSTICO= ss.t.ppf(1-(alfa/2), N-1)
  Li=media_muestral - ESTADÍSTICO*(desv_muestral/(N**0.5))
  Ls=media_muestral + ESTADÍSTICO*(desv_muestral/(N**0.5))
  if Li>Ls:
    intervalo='ERROR'
  else:
    INTERVALO=(Li, Ls)
    from IPython.display import display, Math
    intervalo_media=display(Math('IC['+str(round(INTERVALO[0],4))+'\leq \mu \leq'+ str(round(INTERVALO[1],4))+']='+str(1-alfa)))
  return intervalo_media


def IC_VARIANZA(media_muestral, desv_muestral, N, alfa):
   import scipy.stats as ss
   ESTADÍSTICO_1= ss.chi2.ppf(1-(alfa/2), N-1)
   ESTADÍSTICO_2= ss.chi2.ppf((alfa/2), N-1)
   Li=(N-1)*(desv_muestral**2) / ESTADÍSTICO_1
   Ls=(N-1)*(desv_muestral**2) / ESTADÍSTICO_2
   if Li <0 or Li>Ls:
     intervalo='ERROR'
   else:
     INTERVALO=(Li, Ls)
     from IPython.display import display, Math
     intervalo_var=display(Math('IC['+str(round(INTERVALO[0],4))+'\leq \sigma^2 \leq'+ str(round(INTERVALO[1],4))+']='+str(1-alfa)))
   return intervalo_var

In [ ]:
for i in DATA:
  if DATA[i].dtype=='int64' or DATA[i].dtype=='float64':
    print(f"El intervalo de confianza para la media de la variable {i} es:")
    IC_MEDIA_VARDESCON(DATA[i].mean(), DATA[i].std(),len(DATA[i]),0.05)
    print(f"El intervalo de confianza para la varianza de la variable {i} es:")
    IC_VARIANZA(DATA[i].mean(), DATA[i].std(),len(DATA[i]),0.05)

Para otros intervalos ver: https://github.com/TGADEstadisticaI/EstadisticaI/tree/main

###**Test de hipótesis**

Al trabajar con muestras, también nos puede interesar validar algún suposición sobre la verdadera media o varianza de cada variable, principalmente

In [ ]:
def TH_MEDIA_VARDESCON(media_muestral, mu, S, n, alfa, simbolo_H1):
  import scipy.stats as ss
  import numpy as np
  tobs=round((media_muestral-mu) / (S/np.sqrt(n)),4)
  if simbolo_H1=='>':
    talfa  = round(ss.t.ppf(1-alfa, n-1),4)
    if tobs > talfa:
      respuesta='Como se cumple C.D ya que ' + 'tobs='+str(tobs)+' es mayor que '+ 't_1-alfa;n-1='+str(talfa)+' entonces se rechaza H0'
    else:
      respuesta='Como no se cumple C.D ya que ' + 'tobs='+str(tobs)+' es menor que '+ 't_1-alfa;n-1='+str(talfa)+' entonces no se rechaza H0'

    p_valor=round(1-ss.t.cdf(tobs, n-1),8)
    if p_valor < alfa:
      respuesta1='Como se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es menor que '+ 'alfa='+ str(alfa)+' entonces se rechaza H0'
    else:
      respuesta1='Como no se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es mayor que '+ 'alfa='+ str(alfa)+' entonces no se rechaza H0'

  elif simbolo_H1=='<':
    talfa  = round(ss.t.ppf(alfa, n-1),4)
    if tobs < talfa:
      respuesta='Como se cumple C.D ya que ' + 'tobs='+str(tobs)+' es menor que '+ 'talfa;n-1='+str(talfa)+' entonces se rechaza H0'
    else:
      respuesta='Como no se cumple C.D ya que ' + 'tobs='+str(tobs)+' es mayor que '+ 'talfa;n-1='+str(talfa)+' entonces no se rechaza H0'

    p_valor=round(ss.t.cdf(tobs, n-1),8)
    if p_valor < alfa:
      respuesta1='Como se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es menor que '+ 'alfa='+ str(alfa)+' entonces se rechaza H0'
    else:
      respuesta1='Como no se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es mayor que '+ 'alfa='+ str(alfa)+' entonces no se rechaza H0'

  else:
    talfa  = round(ss.t.ppf(1-alfa/2, n-1),4)
    if np.abs(tobs) > talfa:
      respuesta='Como se cumple C.D ya que ' + '|tobs|='+'|'+str(tobs)+'|'+' es mayor que '+ 't_1-alfa/2;n-1='+str(talfa)+' entonces se rechaza H0'
    else:
      respuesta='Como no se cumple C.D ya que ' + '|tobs|='+'|'+str(tobs)+'|'+' es menor que '+ 't_1-alfa/2;n-1='+str(talfa)+' entonces no se rechaza H0'

    p_valor=2*round(1-ss.t.cdf(abs(tobs), n-1),8)
    if p_valor < alfa:
      respuesta1='Como se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es menor que '+ 'alfa='+ str(alfa)+' entonces se rechaza H0'
    else:
      respuesta1='Como no se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es mayor que '+ 'alfa='+ str(alfa)+' entonces no se rechaza H0'

  return respuesta, respuesta1

def TH_MEDIA_VARIANZA(var_muestral, var_pob, n, alfa, simbolo_H1):
  import scipy.stats as ss
  import numpy as np
  chiobs=round((n-1)*var_muestral / var_pob,4)
  if simbolo_H1=='>':
    chialfa  = round(ss.chi2.ppf(1-alfa, n-1),4)
    if chiobs > chialfa:
      respuesta='Como se cumple C.D ya que ' + 'chiobs='+str(chiobs)+' es mayor que '+ 'Chi_1-alfa;n-1='+str(chialfa)+' entonces se rechaza H0'
    else:
      respuesta='Como no se cumple C.D ya que ' + 'chiobs='+str(chiobs)+' es menor que '+ 'Chi_1-alfa;n-1='+str(chialfa)+' entonces no se rechaza H0'

    p_valor=round(1-ss.chi2.cdf(chiobs, n-1),8)
    if p_valor < alfa:
      respuesta1='Como se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es menor que '+ 'alfa='+ str(alfa)+' entonces se rechaza H0'
    else:
      respuesta1='Como no se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es mayor que '+ 'alfa='+ str(alfa)+' entonces no se rechaza H0'

  elif simbolo_H1=='<':
    chialfa  = round(ss.chi2.ppf(alfa, n-1),4)
    if chiobs < chialfa:
      respuesta='Como se cumple C.D ya que ' + 'chiobs='+str(chiobs)+' es menor que '+ 'chialfa;n-1='+str(chialfa)+' entonces se rechaza H0'
    else:
      respuesta='Como no se cumple C.D ya que ' + 'chiobs='+str(chiobs)+' es mayor que '+ 'chialfa;n-1='+str(chialfa)+' entonces no se rechaza H0'

    p_valor=round(ss.chi2.cdf(chiobs, n-1),8)
    if p_valor < alfa:
      respuesta1='Como se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es menor que '+ 'alfa='+ str(alfa)+' entonces se rechaza H0'
    else:
      respuesta1='Como no se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es mayor que '+ 'alfa='+ str(alfa)+' entonces no se rechaza H0'

  else:
    chialfa  = round(ss.chi2.ppf(1-alfa/2, n-1),4)
    if np.abs(chiobs) > chialfa:
      respuesta='Como se cumple C.D ya que ' + '|chiobs|='+'|'+str(chiobs)+'|'+' es mayor que '+ 'Chi_1-alfa/2;n-1='+str(chialfa)+' entonces se rechaza H0'
    else:
      respuesta='Como no se cumple C.D ya que ' + '|chiobs|='+'|'+str(chiobs)+'|'+' es menor que '+ 'Chi_1-alfa/2;n-1='+str(chialfa)+' entonces no se rechaza H0'

    p_valor=2*np.min([round(1-ss.chi2.cdf(chiobs, n-1),8), round(ss.chi2.cdf(chiobs, n-1),8)])
    if p_valor < alfa:
      respuesta1='Como se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es menor que '+ 'alfa='+ str(alfa)+' entonces se rechaza H0'
    else:
      respuesta1='Como no se cumple C.D ya que ' + 'P-valor='+str(p_valor)+  ' es mayor que '+ 'alfa='+ str(alfa)+' entonces no se rechaza H0'

  return respuesta, respuesta1

In [ ]:
TH_MEDIA_VARIANZA(DATA[i].var(), 30,  len(DATA[i]),0.05, '>')

In [ ]:
#aplicarlos a todoas juntas teniendo en cuenta que se esta fijando un único valor de parámetro poblacional (si no correr de manera individual)
for i in DATA:
  if DATA[i].dtype=='int64' or DATA[i].dtype=='float64':
    print(f"El resultado del test de hipótesis para la media de la variable {i} es: {TH_MEDIA_VARDESCON(DATA[i].mean(), 20 ,DATA[i].std(),len(DATA[i]),0.05,'>')[0]}")
    print(f"El resultado del test de hipótesis para la media de la variable {i} es: {TH_MEDIA_VARDESCON(DATA[i].mean(), 20 ,DATA[i].std(),len(DATA[i]),0.05,'>')[1]}")
    print(f"El resultado del test de hipótesis para la varianza de la variable {i} es: {TH_MEDIA_VARIANZA(DATA[i].var(), 30,  len(DATA[i]),0.05, '>')[0]}")
    print(f"El resultado del test de hipótesis para la varianza de la variable {i} es: {TH_MEDIA_VARIANZA(DATA[i].var(), 30,  len(DATA[i]),0.05, '>')[1]}")

Para otros test ver: https://github.com/TGADEstadisticaI/EstadisticaI/tree/main